title: Python wild - Hop de kikker
hero_image: images/banner.png
description: Maak een cartoonkikker die springt, zich uitrekt en in elkaar zakt terwijl hij door je code huppelt.
meta_title: Leer programmeren met Python Wild | Hop de kikker
meta_description: Leer Python met de Raspberry Pi Foundation. Programmeer een cartoonkikker die huppelt en zich uitrekt met animatie.
version: 1
listed: true
copyedit: false
last_tested: "2025-04-11"
steps:
  - title: step_1
  - title: step_2
    completion:
        - engaged
  - title: step_3
  - title: step_4
  - title: step_5
  - title: step_6
  - title: step_7
  - title: step_8
    completion:
      - internal
      - external
