title: Python wild - Hop the frog
hero_image: images/banner.png
description: Make a cartoon frog that jumps, stretches, and squashes as it hops through your code.
meta_title: Learn to code with Python Wild | Hop the Frog
meta_description: Learn Python with the Raspberry Pi Foundation. Code a cartoon frog that hops and stretches with animation.
version: 1
listed: true
copyedit: false
last_tested: "2025-04-11"
steps:
  - title: step_1
  - title: step_2
    completion:
        - engaged
  - title: step_3
  - title: step_4
  - title: step_5
  - title: step_6
  - title: step_7
  - title: step_8
    completion:
      - internal
      - external
